#include <fstream>

#include <sys/capability.h>
#include <sys/prctl.h>
#include <sys/resource.h>

signed main() {
    std::ofstream out("constants.py");
    out << "\"\"\"\n";
    out << "This file was automatically generated by selfeval.\n";
    out << "Selfeval would use constants below to adapt macros in your Linux/glibc.\n";
    out << "Please DO NOT modify it unless you know what you are doing !\n";
    out << "\"\"\"\n";
    out << "\n";
    out << "# sys/resource.h\n";
    out << "RLIM_INFINITY = " << RLIM_INFINITY << '\n';
    out << "\n";
    out << "# sys/capability.h\n";
    out << "CAP_SETGID = " << CAP_SETGID << '\n';
    out << "CAP_SETUID = " << CAP_SETUID << '\n';
    out << "CAP_SYS_NICE = " << CAP_SYS_NICE << '\n';
    out << "CAP_EFFECTIVE = " << CAP_EFFECTIVE << '\n';
    out << "CAP_PERMITTED = " << CAP_PERMITTED << '\n';
    out << "CAP_INHERITABLE = " << CAP_INHERITABLE << '\n';
    out << "CAP_SET = " << CAP_SET << '\n';
    out << "PR_SET_KEEPCAPS = " << PR_SET_KEEPCAPS << '\n';
    return 0;
}