import os
from pathlib import Path

src = Path("src")
home = Path(os.path.expanduser("~"))

rc_sh = """if [ -f ~/.selfeval.sh ]; then
    . ~/.selfeval.sh
fi"""
main_sh = f"""# selfeval.sh
# This file was automatically generated by selfeval.
# It provides shell integration for selfeval.
# Please DO NOT modify it unless you know what you are doing !

alias selfeval="{os.getcwd()}/run.sh"
"""

with open(home / ".bashrc") as file:
    text = file.read()
if text.find(rc_sh) == -1:
    with open(home / ".bashrc", "a") as file:
        file.write("\n# installed by selfeval\n")
        file.write(rc_sh)
        file.write("\n")
with open(home / ".selfeval.sh", "w") as file:
    file.write(main_sh)
